/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.pru.fancy.api;

import com.pru.fancy.model.UploadFile200Response;
import io.swagger.annotations.*;
import io.swagger.v3.oas.annotations.Parameter;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.constraints.*;
@Validated
@Api(value = "Default", description = "the Default API")
public interface DefaultApi {
    

  @ApiOperation(value = "Upload a file", nickname = "uploadFile", notes = "Upload a file to the server and save it to the specified directory.", response = UploadFile200Response.class  )
    @ApiResponses({ @ApiResponse(code = 200, message = "File uploaded successfully", response = UploadFile200Response.class),@ApiResponse(code = 400, message = "Bad request. No file was uploaded or an error occurred.", response = String.class) })
     @RequestMapping(method = RequestMethod.POST,
            value = "/fileupload/upload",
            produces = { "application/json" },
            consumes = { "multipart/form-data" })
    ResponseEntity<UploadFile200Response> uploadFile(@Parameter(name = "file", description = "The file to be uploaded.") @RequestPart(value = "file", required = false) MultipartFile file);
      
}
